"""
Here the qrcode creation processes and manipulation of the qr images created by the system are executed
https://pypi.org/project/qrcode/
"""
import qrcode
import random
import os

path = "src/assets/"

def generate_qrcode(content: str) -> str:
    """
    Using the qrcode library we will generate a qrcode containing the information entered by the user.
    A number is generated by the random library so that its last 5 digits are the name of the qrcode with the extension ".png"

    * Args:
        \t - content (str): User-entered content
    * Returns:
        \t - full_path (str): Generated qrcode image path
    """
    random.seed()
    img_name = str(random.random())[-5::]
    img_type = ".png"
    full_path = path + img_name + img_type

    img = qrcode.make(content)
    img.save(full_path)
    return full_path

def erase_qrcode():
    """
    Cleans the directory where the images are saved to avoid accumulation of images
    """
    for item in os.listdir(path):
        path_item = os.path.join(path, item)
        os.remove(path_item)
